CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS auth_schema;
CREATE SCHEMA IF NOT EXISTS task_schema;
CREATE SCHEMA IF NOT EXISTS submission_schema;
CREATE SCHEMA IF NOT EXISTS user_schema;